config/routes.rb
Rails.application.routes.draw do
  devise_for :users

   authenticated :user do
    root 'admin#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

   get 'contact' => 'home#contact_us'
   get 'complaints' => 'home#complaints'
   get 'admin' => 'admin#index'
   get 'committee_members' => 'home#committee_members'
   get 'message_chairperson' => 'home#message_chairperson'
   get 'message_executive' => 'home#message_executive'
   get 'ongoing_projects' => 'home#ongoing_projects'
   get 'future_projects' => 'home#future_projects'
   get 'about_board' => 'home#about_board'
   get 'tender_and_notice' => 'home#tender_and_notice'
   get 'special_member' => 'home#special_member'
   get 'services' => 'home#services'
   get 'assets' => 'home#assets'
   get 'past_bearers' => 'home#past_bearers'

    resources :complaints
    resources :tenders
    resources :messages

end

app/models/complaint.rb
# == Schema Information
#
# Table name: complaints
#
#  id          :integer          not null, primary key
#  sender      :string(255)
#  title       :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  email       :string(255)
#  mobile      :string(255)
#

class Complaint < ActiveRecord::Base
	validates :sender, :email, :mobile, :title, :description, presence: true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  email       :string(255)
#  mobile      :string(255)
#  title       :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Message < ActiveRecord::Base
	validates :name, :email, :mobile, :title, :description, presence: true
end

app/models/tender.rb
# == Schema Information
#
# Table name: tenders
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  file       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Tender < ActiveRecord::Base
	mount_uploader :file, FileUploader 
	validates :title, :file, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController 
	before_action :authenticate_user!
	def index 
		@complaints = Complaint.all
		@messages = Message.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # http_basic_authenticate_with name: "biswanathchariali", password: "biswath123", except: :index
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController 
	def create
	@complaint = Complaint.new(complaints_params)
    respond_to do |format|
      if @complaint.save
        format.html { redirect_to root_url, notice: 'News was successfully created.' }
      else
        format.html { redirect_to :complaints_path }
      end
    end
	end

	def destroy
		@complaint = Complaint.find(params[:id])
		@complaint.destroy
		respond_to do |format|
         format.html { redirect_to admin_url, notice: 'News was successfully destroyed.' }
         format.json { head :no_content }
        end
	end

	private 

	def complaints_params 
		params.require(:complaint).permit(:title, :sender, :description, :email, :mobile)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# http_basic_authenticate_with name: "biswanathchariali", password: "biswath123", except: :index

	def index
	end

	def tender_and_notice
		@tenders = Tender.all
	end

	def 

	def contact_us
	end

	def about_board
	end

	def special_member
	end

	def services 
	end

	def assets
	end

	def complaints
	end

	def committee_members
	end

	def message_chairperson
	end

	def message_executive
	end

	def special_member
	end

	def past_bearers
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 
	before_action :authenticate_user!, only: [:destroy]
	def new
 		@message = Message.new
 	end
 	def create
	@message = Message.new(messages_params)
    respond_to do |format|
      if @message.save
        format.html { redirect_to root_url, notice: 'News was successfully created.' }
      else
        format.html { redirect_to :root_path }
      end
    end
	end

	def destroy
		@message = Message.find(params[:id])
		@message.destroy
		respond_to do |format|
         format.html { redirect_to admin_url, notice: 'News was successfully destroyed.' }
         format.json { head :no_content }
        end
	end

	private 

	def messages_params 
		params.require(:message).permit(:title, :name, :mobile, :description)
	end
end

app/controllers/tenders_controller.rb
 class TendersController < ApplicationController 

 	before_action :authenticate_user!

 	def new
 		@tender = Tender.new
 	end
 	def create
	@tender = Tender.new(tenders_params)
    respond_to do |format|
      if @tender.save
        format.html { redirect_to tender_and_notice_url, notice: 'News was successfully created.' }
      else
        format.html { redirect_to :projects_path }
      end
    end
	end

	def destroy
		@tender = Tender.find(params[:id])
		@tender.destroy
		respond_to do |format|
         format.html { redirect_to tender_and_notice_url, notice: 'News was successfully destroyed.' }
         format.json { head :no_content }
        end
	end

	private 

	def tenders_params 
		params.require(:tender).permit(:title, :file)
	end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="admin-container">

    <div style="height: 90px;"></div>

    <div>
        <%= link_to 'add tender', new_tender_path, :class => 'add-tender-button' %>
    </div>

    <div class="form-style-90">
        <h3 class="about-heading">Listing complaints</h3>
        <% if @complaints.length === 0 %>
            <h5>No any Feedback</h5>
        <% end %>
        <div class="numberlist" style="overflow-x: auto;">
            <table>
              <thead>
                    <tr>
                    <th>Sl no.</th>
                    <th>Name of Sender</th>
                    <th>Title of Complaint</th>
                    <th>Email of Sender</th>
                    <th>Mobile of Sender</th>
                    <th>Complain in Details</th>
                   <% if current_user %> <th>Remove</th> <% end %>
                  </tr>
              </thead>
                <tbody>
                    <% i = 0 %>
                    <% @complaints.each do |complaint| %>
                    <% i = i.to_i + 1%>
                    <tr>
                        <td><%= i %></td>
                        <td><%= complaint.sender %></td>
                        <td><%= complaint.title %></td>
                        <td><%= complaint.email %></td>
                        <td><%= complaint.mobile %></td>
                        <td><%= complaint.description %></td>
                      <% if current_user %>  <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td> <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>


    <div class="form-style-90">
        <h3 class="about-heading">Listing Messages</h3>
        <% if @messages.length === 0 %>
            <h5>No any Messages</h5>
        <% end %>
        <div class="numberlist" style="overflow-x: auto;">
            <table>
              <thead>
                    <tr>
                    <th>Sl no.</th>
                    <th>Name of Sender</th>
                    <th>Title of Complaint</th>
                    <th>Complain in Details</th>
                   <% if current_user %> <th>Remove</th> <% end %>
                  </tr>
              </thead>
                <tbody>
                    <% i = 0 %>
                    <% @messages.each do |message| %>
                    <% i = i.to_i + 1%>
                    <tr>
                        <td><%= i %></td>
                        <td><%= message.name %></td>
                        <td><%= message.title %></td>
                        <td><%= message.description %></td>
                      <% if current_user %>  <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td> <% end %>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>

</div>

app/views/home/about_board.html.erb
<div class="about-board-container">
  <div style="height: 90px;"></div>

    <section class="about" id="about">
      <h2 class="about-heading text-center">About Biswanath Chariali Municipal Board</h2>

      <div class="row about-description">
      <div class="col-md-7">
        <div class="about-text">
          <p>
            Biswanath Chariali is the headquater of Biswanath district in Central Assam. The culturally vibrant city derived its name from sacred Biswanath Ghat. The sacrosanct
          ghat on bank of mighty Brahmaputra, has a cluster of temples, and is also known as Gupt Kashi, in comparison with holy city of Kashi during golden rule of Guptas. The city is now proud of its new Clock Tower (Ghanta Ghar), the first of its kind in Assam.
          </p>

          <p>
            On July 1970, a four-member Biswanath Chariali Town Committee was born with four wards under guardianship of veteran freedom fighter Late Cheniram Das as its founder Chairmen. After 41 glorious year of service, on March 21 2011, the town committee was upgraded to Biswanath Chariali Municipal Board, and its ambit was widened to eight wards.
          </p>

           <p>
             Sri Dilip Baruah, who was last elected Chairperson of town committee, shouldered the responsibility of Founder Chairperson of new municipal board. At present Biswanath Chariali Municipal Board is led by Smti Ruli Sharma as chairperson.
           </p>
        </div>
      </div>
      <div class="col-md-5">
        <div class="video-div">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/qOXdwbYs6a4?ecver=2"></iframe>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/home/assets.html.erb
 <div class="committee-member-container">
	<div style="height: 90px;"></div>
<% @assets = [

	   {
		'details' => 'Biswanath Chariali Municipal Board (BCMB) is operating one bi-weekly market at Madhupur, where trade commences on Sundays and Thursdays. The BCMB is planning to redesign the existing market to a modern and hygienic one.'
		},
		{
		'details' => 'BCMB runs two daily markets at BG Road and Kochgaon. There is another market shed at Bamgaon under the municipal board.'
		},
		{
		'details' => 'BCMB has three commercial buildings, rented out to traders at Kochgaon, Madhupur and BG Road.'
		},
		{
		'details' => 'BCMB has been maintaining two parks and one library in Biswanath Charliali. '
		},
		{
		'details' => 'One state of the art auditorium is under construction and is likely to be completed soon.'
		}
	] %>

<div class="form-style-90">
	 <h3 class="about-heading">Assets</h3>

 	<div class="numberlist" style="overflow-x: auto;">
		<table>
		  <thead>
				<tr>
					<th>Sl no.</th>
			    <th class="text-align-th">Our Assets</th>
			  </tr>
		  </thead>
			<tbody>
				<% i = 0 %>
				<% @assets.each do |asset| %>
				<% i = i.to_i + 1%>
				<tr>
					<td><%= i %></td>
					<td><%= asset['details'] %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
 	</div>
</div>
</div>

app/views/home/committee_members.html.erb
<div class="committee-member-container">
	<div style="height: 90px;"></div>
<% @committee_members = [

	   {
		'name' => 'Sri Pratap Saikia ',
		'contact_no' => '9435040377',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Smti Rita Mahanta ',
		'contact_no' => '8638514438',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Sri Rupok Das Gupta ',
		'contact_no' => '9954011366',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Smti Ruli Sarmah, Chairperson    ',
		'contact_no' => '9401067900',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Smti Taposhi Saha ',
		'contact_no' => '9435505535',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Smti Madhobi Sarkar',
		'contact_no' => '9707688100',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Sri Anjan Borah',
		'contact_no' => '9435982723',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Sri Dipak Deka ',
		'contact_no' => '8011077559',
		'email_id' => '',
		'picture' => ''
		},

		{
		'name' => 'Sri Biman Saikia',
		'contact_no' => '9435853556',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Smti Bithika Sen, Vice Chairperson',
		'contact_no' => '8011845036',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Sri Manuj Borah',
		'contact_no' => '9435383822',
		'email_id' => '',
		'picture' => ''
		},
		{
		'name' => 'Miss Ashma Sultana',
		'contact_no' => '8638451793',
		'email_id' => '',
		'picture' => ''
		}

	] %>

<div class="form-style-90">
	 <h3 class="about-heading">Ward Commissioners</h3>
 	<div class="numberlist" style="overflow-x: auto;">
		<table>
		  <thead>
				<tr>
					<th>Ward No.</th>
			    <th>Ward Commissioners</th>
			    <th>Mobile Number</th>
			  </tr>
		  </thead>
			<tbody>
				<% i = 0 %>
				<% @committee_members.each do |member| %>
				<% i = i.to_i + 1%>
				<tr>
					<td><%= i %></td>
					<td><%= member['name'] %></td>
					<td><%= member['contact_no'] %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
 	</div>
</div>
</div>

app/views/home/complaints.html.erb
<div class="complaint-container">
  <div style="height: 90px;"></div>

   <div class="container">
     <div style="display: flex; justify-content: space-around; margin-top: 30px; flex-wrap: wrap">
     <div style="flex: 1; padding-right: 15px;">
       <h3 class="form-style-9-header">Leave us a Message</h3>
       <p style="font-size: 15px; line-height: 1.6em;">
         If you have a complaint or a grievance, please feel free to write to our Complaint Centre. We promise to look into your complaint and take the appropriate measures at the earliest.
       </p>
     </div>

   	<%= form_for Complaint.new, url: complaints_path, html: {class: "form-style-9"} do |f| %>
  	  <ul>
    	  <li>
  	  		<%= f.text_field :title, :class => 'field-style field-split align-left', :placeholder => 'Title For Complaint' %>
          <%= f.text_field :sender, :class => 'field-style field-split align-right', :placeholder => 'Your Fullname' %>
    	  </li>
        <li>
          <%= f.text_field :email, :class => 'field-style field-split align-left', :placeholder => 'Your Email' %>
          <%= f.text_field :mobile, :class => 'field-style field-split align-right', :placeholder => 'Your Mobile' %>
        </li>
        <li>
          <%= f.text_area :description, :class => 'field-style complaint-textarea', :placeholder => 'Write Your Complaint Here' %>
        </li>
        <li><%= f.submit "Submit" %></li>
  	  </ul>
  	<% end %>
    </div>
   </div>

</div>

app/views/home/contact_us.html.erb
 <div class="contact-us-container">
   <div style="height: 90px;"></div>

 <div class="container">
  <h3 class="about-heading">Contact us</h3>
  <div class="contact-us-address">
    <div class="form-style-10">
       <section>
         <div>
           <h3 class="address-heading">Our Address</h3>
           <div class="contact-address-container">
             <div class="address" style="flex: 1">
               <div class="icon-location">
                 <i class="fa fa-map-marker" aria-hidden="true"></i>
               </div>
               <div class="myaddress">
                 <p class="about-text">Biswanath Charliali Municipality Board<br>
                   BG Road, Near Post Office<br>
                   Biswanath Chariali, Dist: Biswanath <br>
                 Assam, India.<br>
                 Assam-784176</p>
               </div>
             </div>
           <div style="flex: 1">
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-phone" aria-hidden="true"></i>
               </div>
               <div class="myaddress" style="flex: 1">
                 <p class="about-text">Help Desk- 03715-222059</p>
               </div>
             </div>
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-phone" aria-hidden="true"></i>
               </div>
               <div class="myaddress" style="flex: 1">
                 <p class="about-text">Chairperson- 9401067900</p>
               </div>
             </div>
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-phone" aria-hidden="true"></i>
               </div>
               <div class="myaddress" style="flex: 1">
                 <p class="about-text">Executive Officer- 8011003249</p>
               </div>

             </div>

           </div>
           <!-- <div class="social-icons" style="flex: 1">
             <a class="social-icon facebook">
               <i class="fa fa-facebook"></i>
               <i class="fa fa-facebook"></i>
             </a>
             <a class="social-icon google">
               <i class="fa fa-google-plus"></i>
               <i class="fa fa-google-plus"></i>
             </a>
             <a class="social-icon twitter">
               <i class="fa fa-twitter"></i>
               <i class="fa fa-twitter"></i>
             </a>
           </div> -->
           <div style="flex: 1">
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-phone" aria-hidden="true"></i>
               </div>
               <div class="myaddress" style="flex: 1">
                 <p class="about-text">Sanitary Branch- 8011967522</p>
               </div>
             </div>
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-phone" aria-hidden="true"></i>
               </div>
               <div class="myaddress" style="flex: 1">
                 <p class="about-text">Engineering Branch- 9435182860</p>
               </div>
             </div>
             <div class="address">
               <div class="icon-location">
                 <i class="fa fa-envelope" aria-hidden="true" style="font-size: 23px"></i>
               </div>
               <div class="myaddress">
                 <p class="about-text">biswanathchariali.tc@gmail.com</p>
               </div>
             </div>
           </div>
         </div>

        </div>
      </section>
    </div>
  </div>
  <div class="contact-us-form-address">
    <div class="contact-us-form">
      <%= form_for Message.new, url: messages_path, html: {class: "form-style-9"} do |f| %>
       <ul>
          <li>
            <%= f.text_field :name, :class => 'field-style field-split align-left', :placeholder => 'Your Name' %>
            <%= f.text_field :email, :class => 'field-style field-split align-right', :placeholder => 'Your Email' %>
         </li>
         <li>
          <%= f.text_field :mobile, :class => 'field-style field-split align-left', :placeholder => 'Mobile' %>
          <%= f.text_field :title, :class => 'field-style field-split align-right', :placeholder => 'Your Topic or Subject' %>
         </li>
        <li> <%= f.text_area :description, :class => 'field-style', :placeholder => 'Write Your Description Here' %></li>
        <li><%= f.submit "Submit" %></li>
      </ul>
     <% end %>
     <div class="social-icons" style="flex: 1">
       <a class="social-icon facebook">
         <i class="fa fa-facebook"></i>
         <i class="fa fa-facebook"></i>
       </a>
       <a class="social-icon google">
         <i class="fa fa-google-plus"></i>
         <i class="fa fa-google-plus"></i>
       </a>
       <a class="social-icon twitter">
         <i class="fa fa-twitter"></i>
         <i class="fa fa-twitter"></i>
       </a>
     </div>
    </div>


    <div class="contact-google-map" id="map"></div>
  </div>
 </div>

 </div>

app/views/home/future_projects.html.erb
<div class="future-project-container">
<div style="height: 90px;"></div>
<% @future_projects = [

	{
		'name' => '3rd Finance',
		'sector' => 'State ',
		'work' => 'Road Construction and Paid Electricity Dues ',
		'amount' => '3792418/- ',
		'funding' => 'SFC',
		'construction_year' => '2010-11 ',
		'status' => '30% Complete',
		'coverage' => ''
		},
		{
		'name' => 'DDP ',
		'sector' => 'State  ',
		'work' => 'Road Construction and Community Stage ',
		'amount' => '1049222/- ',
		'funding' => 'DMA ',
		'construction_year' => '2010-11  ',
		'status' => '82% Complete',
		'coverage' => ''
		},
		{
		'name' => 'SJSRY',
		'sector' => 'Central and State ',
		'work' => 'Auditorium Hall at Bhupen Hazarika Park ',
		'amount' => '1600000/-  ',
		'funding' => 'DMA ',
		'construction_year' => '2009-10  ',
		'status' => 'under process',
		'coverage' => ''
		},
		{
		'name' => 'SJSRY',
		'sector' => 'Central and State ',
		'work' => 'Auditorium Hall at Bhupen Hazarika Park ',
		'amount' => '1500000/-  ',
		'funding' => 'DMA ',
		'construction_year' => '2010-11',
		'status' => 'under process',
		'coverage' => ''
		},

	] %>

	<div class="form-style-90">
	 <h3 class="about-heading">Future Projects</h3>
 	 <div class="numberlist" style="overflow-x: auto;">
		<table>
		  <thead>
				<tr>
					<th>Sl no.</th>
			    <th>Name of Project</th>
			    <th>Sector</th>
			    <th>Name of the work</th>
					<th>Amount (Rs.)</th>
					<th>Funding By</th>
					<th>Years of Construction</th>
					<th>Status</th>
					<th>Coverage</th>
			  </tr>
		  </thead>
			<tbody>
				<% i = 0 %>
				<% @future_projects.each do |project| %>
				<% i = i.to_i + 1%>
				<tr>
					<td><%= i %></td>
					<td><%= project['name'] %></td>
					<td><%= project['sector'] %></td>
					<td><%= project['work'] %></td>
					<td><%= project['amount'] %></td>
					<td><%= project['funding'] %></td>
					<td><%= project['construction_year'] %></td>
					<td><%= project['status'] %></td>
					<td><%= project['coverage'] %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
 	</div>
</div>

</div>

app/views/home/message_chairperson.html.erb
 <div class="container-message-chairperson">
    <div style="height: 90px;"></div>
      <div class="container">
        <section class="chairperson">
         <h2 class="chairperson-heading text-center">Message from the Chairperson</h2>
          <div class="chairperson-img-description">
            <div class="chairperson-img">
              <img src="../images/chairperson.png" class="img-responsive">
            </div>
            <div class="chairperson-description">
              <p class="text-justify">It is a proud moment for me to dedicate this website to the people of Biswanath Chariali. </p>

              <p class="text-justify">After taking charge of this Municipal Board, I have been striving to make Biswanath Charliali a modern and well planed town and serve the residents of this town with dedication.
              There are a number of roadblocks that we need to overcome to achieve are target of modern, planned, green and clean Biswanath Chariali. But I am confident that with the support and guidance of all of you, we will make it possible very soon.</p>

              <p class="text-justify">  A website is a great tool to connect with people and roll out services.  We are also planning to roll out online payment of taxes, online service request etc through this website very soon. This website also provides links to our social media accounts like Twitter and Facebook, through which we expect frequent interaction between the Board and our esteemed townsfolk, especially the new generation. </p>

              <p class="text-justify">Let us exchange ideas and help each other to make Biswanath Charliali a smart town. 
              I also take this opportunity to thank everyone who has contributed immensely in creating this website and to everyone having shown trust in me in serving the people with pride.
              </p>
              <%= image_tag 'sign.png' %>
            </div>
          </div>
        </section>
      </div>
    </div>

app/views/layouts/_navbar.html.erb
  <nav class="custom-navbar navbar-default navbar-fixed-top">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to root_path, :class => 'navbar-brand' do %>
            <%= image_tag("logo.png", :alt => "logo img", :class => 'navbar-brand-img img-responsive') %>
          <% end %>

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li data-section="#home"><%= link_to 'Home', root_path, :tabindex => '-1' %></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About us<span class="caret"></span></a>
              <ul class="dropdown-menu" style="text-align: center;background-color: rgba(0,0,0,0.7);">
                <li><%= link_to 'Message of Local MLA & Invitee Member', special_member_path, :tabindex => '-1' %></li>
                <li><%= link_to 'Message of Executive Officer', message_executive_path, :tabindex => '-1' %></li>
                <!-- <li><%= link_to 'Past Members', past_bearers_path, :tabindex => '-1' %></li> -->
                <li><%= link_to 'Services', services_path, :tabindex => '-1' %></li>
                <li><%= link_to 'Assets', assets_path, :tabindex => '-1' %></li>
                <li><%= link_to 'Ward Commissioners', committee_members_path, :tabindex => '-1' %></li>
                <li><%= link_to 'Past Office Bearers', past_bearers_path, :tabindex => '-1' %></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
              <ul class="dropdown-menu" style="text-align: center;background-color: rgba(0,0,0,0.7);">
                <li><%= link_to 'Ongoing Projects', ongoing_projects_path, :tabindex => '-1' %></li>
                <li><%= link_to 'Future Projects', future_projects_path, :tabindex => '-1' %></li>
              </ul>
            </li>

            <li><%= link_to 'Tender / Notice', tender_and_notice_path, :tabindex => '-1' %></li>
            <li data-section="#complaints"><%= link_to 'Feedback', complaints_path, :tabindex => '-1' %></li>
            <li data-section="#contact"><%= link_to 'Contact Us', contact_path, :tabindex => '-1' %></li>
            <% if current_user %>
              <li >
                <%= link_to 'Logout', destroy_user_session_path ,method: :delete %>
             </li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>

app/views/tenders/new.html.erb
<div class="new-tender-container">
	
	<div style="height: 90px;"></div>

	 <div>
	 	<h3 class="text-center form-style-9-header">Make New Tender</h3>
	 	<%= form_for @tender, url: tenders_path, html: {class: "form-style-9 form-size450"} do |f| %>
		  <ul>
		  
		 <li> <%= f.text_field :title, :class => 'field-style field-full', :placeholder => 'Title of Tender' %></li>
		 <li> <%= f.file_field :file, :class => 'field-style field-full', :placeholder => 'Write Your Complaint Here' %></li>
		  <li><%= f.submit "Submit" %></li>
		  </ul>
		<% end %>
	</div>
</div>